InfiniTensor/ntops

- src/ntops/__init__.py
- src/ntops/exp.py
- tests/test_exp.py
```
collected 38 items
tests/test_abs.py ........                                               [ 21%]
tests/test_add.py ........                                               [ 42%]
tests/test_addmm.py ..                                                   [ 47%]
tests/test_bmm.py ..                                                     [ 52%]
tests/test_div.py ........                                               [ 73%]
tests/test_exp.py ........                                               [ 94%]
tests/test_mm.py .. …
```
> Add `exp` operator

- src/ntops/__init__.py
- src/ntops/gelu.py
- tests/test_gelu.py
```
collected 46 items
tests/test_abs.py ........                                               [ 17%]
tests/test_add.py ........                                               [ 34%]
tests/test_addmm.py ..                                                   [ 39%]
tests/test_bmm.py ..                                                     [ 43%]
tests/test_div.py ........                                               [ 60%]
tests/test_exp.py ........                                               [ 78%] …
```
> Add `gelu` operator

- src/ntops/__init__.py
- src/ntops/mul.py
- tests/test_mul.py
```
collected 54 items
tests/test_abs.py ........                                               [ 14%]
tests/test_add.py ........                                               [ 29%]
tests/test_addmm.py ..                                                   [ 33%]
tests/test_bmm.py ..                                                     [ 37%]
tests/test_div.py ........                                               [ 51%]
tests/test_exp.py ........                                               [ 66%] …
```
> Add `mul` operator

- tests/test_add.py
- tests/test_addmm.py
- tests/utils.py
```
collected 54 items
tests/test_abs.py ........                                               [ 14%]
tests/test_add.py ........                                               [ 29%]
tests/test_addmm.py ..                                                   [ 33%]
tests/test_bmm.py ..                                                     [ 37%]
tests/test_div.py ........                                               [ 51%]
tests/test_exp.py ........                                               [ 66%] …
```
> Use custom `gauss`

- src/ntops/__init__.py
- src/ntops/rsqrt.py
- tests/test_rsqrt.py
```
collected 62 items
tests/test_abs.py ........                                               [ 12%]
tests/test_add.py ........                                               [ 25%]
tests/test_addmm.py ..                                                   [ 29%]
tests/test_bmm.py ..                                                     [ 32%]
tests/test_div.py ........                                               [ 45%]
tests/test_exp.py ........                                               [ 58%] …
```
> Add `rsqrt` operator

- src/ntops/kernels/relu.py
- src/ntops/torch.py
- tests/test_relu.py
```
collected 70 items
tests/test_abs.py ........                                                   [ 11%]
tests/test_add.py ........                                                   [ 22%]
tests/test_addmm.py ..                                                       [ 25%]
tests/test_bmm.py ..                                                         [ 28%]
tests/test_div.py ........                                                   [ 40%]
tests/test_exp.py ........                                                   [ 51%] …
```
> Add `relu` operator

- src/ntops/kernels/sin.py
- src/ntops/torch.py
- tests/test_sin.py
```
collected 70 items
tests/test_abs.py ........                                                   [ 11%]
tests/test_add.py ........                                                   [ 22%]
tests/test_addmm.py ..                                                       [ 25%]
tests/test_bmm.py ..                                                         [ 28%]
tests/test_div.py ........                                                   [ 40%]
tests/test_exp.py ........                                                   [ 51%] …
```
> Add `sin` operator

- src/ntops/kernels/cos.py
- src/ntops/torch.py
- tests/test_cos.py
```
collected 70 items
tests/test_abs.py ........                                                   [ 11%]
tests/test_add.py ........                                                   [ 22%]
tests/test_addmm.py ..                                                       [ 25%]
tests/test_bmm.py ..                                                         [ 28%]
tests/test_cos.py ........                                                   [ 40%]
tests/test_div.py ........                                                   [ 51%] …
```
> Add `cos` operator

- src/ntops/kernels/sigmoid.py
- src/ntops/torch.py
- tests/test_sigmoid.py
```
collected 70 items
tests/test_abs.py ........                                                   [ 11%]
tests/test_add.py ........                                                   [ 22%]
tests/test_addmm.py ..                                                       [ 25%]
tests/test_bmm.py ..                                                         [ 28%]
tests/test_div.py ........                                                   [ 40%]
tests/test_exp.py ........                                                   [ 51%] …
```
> Add `sigmoid` operator

- src/ntops/__init__.py
```
collected 94 items
tests/test_abs.py ........                                               [  8%]
tests/test_add.py ........                                               [ 17%]
tests/test_addmm.py ..                                                   [ 19%]
tests/test_bmm.py ..                                                     [ 21%]
tests/test_cos.py ........                                               [ 29%]
tests/test_div.py ........                                               [ 38%] …
```
> Expose `torch` via `__all__`

- src/ntops/kernels/tanh.py
- src/ntops/torch.py
- tests/test_tanh.py
> Add `tanh` operator

- src/ntops/kernels/ne.py
- src/ntops/torch.py
- tests/test_ne.py
> Add `ne` operator

- src/ntops/kernels/gt.py
- src/ntops/torch.py
- tests/test_gt.py
> Add `gt` operator

- src/ntops/kernels/ge.py
- src/ntops/torch.py
- tests/test_ge.py
> Add `ge` operator

- src/ntops/kernels/le.py
- src/ntops/torch.py
- tests/test_le.py
> Add `le` operator

- src/ntops/kernels/element_wise.py
```
collected 158 items
tests/test_abs.py ........                                               [  5%]
tests/test_add.py ........                                               [ 10%]
tests/test_addmm.py ..                                                   [ 11%]
tests/test_bmm.py ..                                                     [ 12%]
tests/test_cos.py ........                                               [ 17%]
tests/test_div.py ........                                               [ 22%]
tests/test_eq.py ........ …
```
> Make the `element_wise.arrangement` function accept customizable `block_size` parameter

- src/ntops/kernels/lt.py
- src/ntops/torch.py
- tests/test_lt.py
> Add `lt` operator

- src/ntops/kernels/bitwise_and.py
- src/ntops/torch.py
- tests/test_bitwise_and.py
- tests/utils.py
```
collected 110 items
tests/test_add.py ........                                                   [ 14%]
tests/test_addmm.py ..                                                       [ 16%]
tests/test_bitwise_and.py ................                                   [ 30%]
tests/test_bmm.py ..                                                         [ 32%]
tests/test_cos.py ........                                                   [ 40%]
tests/test_div.py ........ …
```
> Add `bitwise_and` operator

- src/ntops/kernels/bitwise_or.py
- src/ntops/torch.py
- tests/test_bitwise_or.py
- tests/utils.py
```
collected 110 items
tests/test_add.py ........                                                   [ 14%]
tests/test_addmm.py ..                                                       [ 16%]
tests/test_bitwise_or.py ................                                    [ 30%]
tests/test_bmm.py ..                                                         [ 32%]
tests/test_cos.py ........                                                   [ 40%]
tests/test_div.py ........ …
```
> Add `bitwise_or` operator

- src/ntops/kernels/bitwise_not.py
- src/ntops/torch.py
- tests/test_bitwise_not.py
- tests/utils.py
```
collected 110 items
tests/test_add.py ........                                                   [ 14%]
tests/test_addmm.py ..                                                       [ 16%]
tests/test_bitwise_not.py ................                                   [ 30%]
tests/test_bmm.py ..                                                         [ 32%]
tests/test_cos.py ........                                                   [ 40%]
tests/test_div.py ........ …
```
> Add `bitwise_not` operator

- src/ntops/kernels/sub.py
- src/ntops/torch.py
- tests/test_sub.py
```
collected 262 items
tests/test_abs.py ........                                               [  3%]
tests/test_add.py ........                                               [  6%]
tests/test_addmm.py ..                                                   [  6%]
tests/test_bitwise_and.py ................                               [ 12%]
tests/test_bitwise_not.py ................                               [ 19%]
tests/test_bitwise_or.py ................                                [ 25%] …
```
> Add `sub` operator

- src/ntops/kernels/silu.py
- src/ntops/torch.py
- tests/test_silu.py
```
collected 270 items
tests/test_add.py ........                                               [  5%]
tests/test_addmm.py ..                                                   [  6%]
tests/test_bitwise_and.py ................                               [ 12%]
tests/test_bitwise_not.py ................                               [ 18%]
tests/test_bitwise_or.py ................                                [ 24%] …
```
> Add `silu` operator

- src/ntops/kernels/scaled_dot_product_attention.py
- src/ntops/torch.py
- tests/test_scaled_dot_product_attention.py
```
collected 302 items
tests/test_add.py ........                                               [  5%]
tests/test_addmm.py ..                                                   [  5%]
tests/test_bitwise_and.py ................                               [ 11%]
tests/test_bitwise_not.py ................                               [ 16%]
tests/test_bitwise_or.py ................                                [ 21%] …
```
> Add `scaled_dot_product_attention` operator

- src/ntops/kernels/scaled_dot_product_attention.py
```
collected 302 items
tests/test_add.py ........                                               [  5%]
tests/test_addmm.py ..                                                   [  5%]
tests/test_bitwise_and.py ................                               [ 11%]
tests/test_bitwise_not.py ................                               [ 16%]
tests/test_bitwise_or.py ................                                [ 21%] …
```
> Relax the `constexpr` constraints on the shapes of `present_key`, `present_value`, `present_key_slot`, and `present_value_slot`

- tests/test_dropout.py
```
collected 302 items
tests/test_add.py ........                                               [  5%]
tests/test_addmm.py ..                                                   [  5%]
tests/test_bitwise_and.py ................                               [ 11%]
tests/test_bitwise_not.py ................                               [ 16%]
tests/test_bitwise_or.py ................                                [ 21%] …
```
> Remove debug `print` from `test_dropout.py`

- src/ntops/kernels/rms_norm.py
- src/ntops/torch.py
- tests/test_rms_norm.py
```
collected 366 items
tests/test_add.py ........                                               [  4%]
tests/test_addmm.py ..                                                   [  4%]
tests/test_bitwise_and.py ................                               [  9%]
tests/test_bitwise_not.py ................                               [ 13%]
tests/test_bitwise_or.py ................                                [ 18%] …
```
> Add `rms_norm` operator

- src/ntops/kernels/layer_norm.py
- src/ntops/torch.py
- tests/test_layer_norm.py
```
collected 590 items
tests/test_abs.py ........                                               [  1%]
tests/test_add.py ........                                               [  2%]
tests/test_addmm.py ..                                                   [  3%]
tests/test_bitwise_and.py ................                               [  5%]
tests/test_bitwise_not.py ................                               [  8%]
tests/test_bitwise_or.py ................                                [ 11%] …
```
> Add `layer_norm` operator

- tests/test_scaled_dot_product_attention.py
```
platform linux -- Python 3.12.3, pytest-8.4.1, pluggy-1.6.0
rootdir: /home/huang/ntops
plugins: jaxtyping-0.3.2, typeguard-4.4.4, cov-6.2.1, anyio-4.9.0
collected 636 items
tests/test_abs.py ........                                               [  1%]
tests/test_add.py ........                                               [  2%]
tests/test_addmm.py ..                                                   [  2%]
tests/test_bitwise_and.py ................                               [  5%]
tests/test_bitwise_not.py ................                               [  7%]
tests/test_bitwise_or.py ................                                [ 10%]
tests/test_bmm.py …
```
> Skip invalid test cases for `LOWER_RIGHT` causal variant
